"""initial schema

Revision ID: c02fc1116a75
Revises: 
Create Date: 2026-09-15 22:02:26.791476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c02fc1116a75'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_key', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('ASSET', 'LIABILITY', 'EQUITY', 'DIVIDEND', 'REVENUE', 'EXPENSE', 'DRAWING')", name=op.f('ck_accounts_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('code', name=op.f('uq_accounts_code')),
    sa.UniqueConstraint('name_key', name=op.f('uq_accounts_name_key'))
    )
    op.create_table('journal_entries',
    sa.Column('journal_number', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('posting_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("posting_date > '2020-01-01' AND posting_date <= now()", name=op.f('ck_journal_entries_posting_date_range')),
    sa.PrimaryKeyConstraint('journal_number', name=op.f('pk_journal_entries'))
    )
    op.create_table('journal_lines',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('journal_number', sa.BigInteger(), nullable=False),
    sa.Column('line_index', sa.Integer(), nullable=False),
    sa.Column('account', sa.Text(), nullable=False),
    sa.Column('debit_amount', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(debit_amount > 0 AND credit_amount = 0) OR (credit_amount > 0 AND debit_amount = 0)', name=op.f('ck_journal_lines_exactly_one_side')),
    sa.ForeignKeyConstraint(['journal_number'], ['journal_entries.journal_number'], name=op.f('fk_journal_lines_journal_number_journal_entries'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_lines')),
    sa.UniqueConstraint('journal_number', 'line_index', name='uq_journal_lines_journal_number_line_index')
    )
    op.create_table('postings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account', sa.Text(), nullable=False),
    sa.Column('account_key', sa.Text(), nullable=False),
    sa.Column('debit_amount', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('journal_number', sa.BigInteger(), nullable=False),
    sa.Column('posting_date', sa.DateTime(), nullable=False),
    sa.Column('line_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("posting_date > '2020-01-01' AND posting_date <= now()", name=op.f('ck_postings_posting_date_range')),
    sa.CheckConstraint('(debit_amount > 0 AND credit_amount = 0) OR (credit_amount > 0 AND debit_amount = 0)', name=op.f('ck_postings_exactly_one_side')),
    sa.ForeignKeyConstraint(['journal_number'], ['journal_entries.journal_number'], name=op.f('fk_postings_journal_number_journal_entries'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_postings')),
    sa.UniqueConstraint('journal_number', 'line_index', name='uq_postings_journal_number_line_index')
    )
    op.create_index('ix_postings_account_key', 'postings', ['account_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_postings_account_key', table_name='postings')
    op.drop_table('postings')
    op.drop_table('journal_lines')
    op.drop_table('journal_entries')
    op.drop_table('accounts')
    # ### end Alembic commands ###
